### PR TITLE
Bump github.com/np-guard/cloud-resource-collector from 0.4.0 to 0.5.1

### PR DESCRIPTION
**Pull request by olasaadi99**

### CODE REVIEW

**Review by adisos — COMMENTED** [review]
Why did `TestMain` fail in the first commit? what is the difference from the other unit tests in the `unmarshal` of the input configs? 
Why was it required to add `region` and `adderss_prefixes`? Shouldn't `unmarshal` work even if those fields are missing?

**Comment by olasaadi99** [comment]
> Why did `TestMain` fail in the first commit? what is the difference from the other unit tests in the `unmarshal` of the input configs? Why was it required to add `region` and `adderss_prefixes`? Shouldn't `unmarshal` work even if those fields are missing?

all tests failed not just `TestMain`
now it is using the datamodel unmarshel vpc

**Comment by adisos** [comment]
> > Why did `TestMain` fail in the first commit? what is the difference from the other unit tests in the `unmarshal` of the input configs? Why was it required to add `region` and `adderss_prefixes`? Shouldn't `unmarshal` work even if those fields are missing?
> 
> all tests failed not just `TestMain` now it is using the datamodel unmarshel vpc

The collector's unamrshal vpc should work even if those fields are missing

**Review by adisos — COMMENTED** [review]
please add the test from Karen's issue (https://github.com/np-guard/vpc-network-config-analyzer/issues/342) , to TestMain, with the cli args as described in the issue, so we validate that it runs without failure on this example now.

**Review by adisos — APPROVED** [review]

**Pull request merged**
