### PR TITLE
improve unit tests

### PR DESCRIPTION
**Pull request by olasaadi99**

### CODE REVIEW

**Review by ShiriMoran — APPROVED** [review]

**Comment by ShiriMoran** [comment]
@olasaadi99 I see there are 14 dup files in explain_out:
GroupingExternalSG1_all_vpcs_explain.txt and out_GroupingExternalSG1_all_vpcs_explain.txt
and 13 others of the same type: <name> and out_<name>
Please delete the redundant files in a followup PR

**Comment by olasaadi99** [comment]
these files are generated in the test (ignored with gitignore) it is to compare actual and expected (as it is in analysis out tests also)

**Comment by adisos** [comment]
> these files are generated in the test (ignored with gitignore) it is to compare actual and expected (as it is in analysis out tests also)

These files should not be uploaded to the repo (maybe you should update your local gitignore so that it does not get committed)

**Comment by olasaadi99** [comment]
> > these files are generated in the test (ignored with gitignore) it is to compare actual and expected (as it is in analysis out tests also)
> 
> These files should not be uploaded to the repo (maybe you should update your local gitignore so that it does not get committed)

but it is not on the repo..

**Comment by ShiriMoran** [comment]
If these files are generated only for the comparison, please delete them at the end of the process

**Comment by adisos** [comment]
> If these files are generated only for the comparison, please delete them at the end of the process

or there should be added `.gitignore` files to the relevant subdris you added

**Pull request merged**
